name: validate-examples

# always run CI on new commits to any branch
on: push

jobs:
  test:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.7
      - name: validate-examples
        shell: bash
        run: |
          pip install --upgrade jsonschema
          make validate
